import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1781178467139 implements MigrationInterface {
    name = 'InitialSchema1781178467139'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`chat_history\` (\`uuid\` varchar(255) NOT NULL, \`bot_id\` bigint(20) NOT NULL, \`channel_id\` bigint(20) NOT NULL, \`channel_type\` varchar(255) NOT NULL, \`name\` varchar(255) NULL, \`content\` json NOT NULL, \`model\` varchar(255) NOT NULL, \`mode\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, PRIMARY KEY (\`uuid\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
        await queryRunner.query(`CREATE TABLE \`bot_info\` (\`bot_id\` bigint(20) NOT NULL, \`name\` varchar(255) NOT NULL, \`font_color\` varchar(255) NOT NULL DEFAULT '#ffffff', \`background_color\` varchar(255) NOT NULL DEFAULT '#000000', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, PRIMARY KEY (\`bot_id\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
        await queryRunner.query(`CREATE TABLE \`color\` (\`id\` int NOT NULL AUTO_INCREMENT, \`role_id\` bigint(20) NOT NULL, \`color_code\` varchar(255) NOT NULL, \`color_name\` varchar(255) NOT NULL, \`deleted_at\` datetime(6) NULL, \`updated_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
        await queryRunner.query(`CREATE TABLE \`role\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`guild_id\` bigint(20) NOT NULL, \`role_id\` bigint(20) NOT NULL, \`type\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`deleted_at\` datetime(6) NULL, \`updated_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
        await queryRunner.query(`CREATE TABLE \`guild\` (\`id\` bigint(20) NOT NULL, \`name\` varchar(255) NOT NULL, \`lobby_name\` varchar(255) NOT NULL DEFAULT 'ロビー', \`inactive_name\` varchar(255) NOT NULL DEFAULT '墓', \`exclude_names\` varchar(255) NULL, \`silent\` tinyint NOT NULL DEFAULT '0', \`deleted_at\` datetime(6) NULL, \`updated_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
        await queryRunner.query(`CREATE TABLE \`user_setting\` (\`user_id\` bigint(20) NOT NULL, \`nickname\` varchar(255) NULL, \`pref\` varchar(255) NULL, \`birth_date\` datetime NULL, \`model_type\` varchar(255) NOT NULL DEFAULT 'default', \`voice_id\` int NOT NULL DEFAULT '3', \`voice_speed\` float NOT NULL DEFAULT '1', \`voice_pitch\` float NOT NULL DEFAULT '0', \`voice_intonation\` float NOT NULL DEFAULT '1', \`deleted_at\` datetime(6) NULL, \`updated_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`user_id\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` bigint(20) NOT NULL, \`guild_id\` bigint(20) NOT NULL, \`user_name\` varchar(255) NULL, \`type\` varchar(255) NOT NULL DEFAULT 'member', \`last_pick_date\` datetime NULL, \`pick_left\` int NOT NULL DEFAULT '0', \`voice_channel_data\` json NULL, \`deleted_at\` datetime(6) NULL, \`updated_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`, \`guild_id\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
        await queryRunner.query(`CREATE TABLE \`item_rank\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`rare\` varchar(255) NOT NULL, \`rank\` smallint NOT NULL, \`deleted_at\` datetime(6) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_381056f37abd6038609476869d\` (\`rare\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
        await queryRunner.query(`CREATE TABLE \`item\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`icon\` varchar(255) NULL, \`rare\` varchar(255) NOT NULL, \`description\` varchar(255) NULL, \`weight\` smallint NOT NULL DEFAULT '1', \`is_present\` tinyint NOT NULL DEFAULT '0', \`reroll\` smallint NOT NULL DEFAULT '0', \`price\` int NOT NULL DEFAULT '0', \`deleted_at\` datetime(6) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
        await queryRunner.query(`CREATE TABLE \`gacha\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` bigint(20) NOT NULL, \`item_id\` bigint NOT NULL, \`pick_date\` datetime NOT NULL, \`is_used\` tinyint NOT NULL DEFAULT '0', \`deleted_at\` datetime(6) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
        await queryRunner.query(`CREATE TABLE \`log\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`bot_id\` bigint(20) NOT NULL DEFAULT '985693983055437864', \`guild_id\` bigint(20) NULL, \`channel_id\` bigint(20) NULL, \`user_id\` bigint(20) NULL, \`level\` varchar(255) NOT NULL, \`event\` varchar(255) NOT NULL, \`message\` text NULL, \`deleted_at\` datetime(6) NULL, \`updated_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
        await queryRunner.query(`CREATE TABLE \`music\` (\`guild_id\` bigint(20) NOT NULL, \`channel_id\` bigint(20) NOT NULL, \`music_id\` smallint NOT NULL, \`title\` varchar(255) NOT NULL, \`url\` varchar(255) NOT NULL, \`thumbnail\` varchar(255) NOT NULL, \`is_play\` tinyint NOT NULL DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`guild_id\`, \`channel_id\`, \`music_id\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
        await queryRunner.query(`CREATE TABLE \`music_info\` (\`guild_id\` bigint(20) NOT NULL, \`channel_id\` bigint(20) NOT NULL, \`is_shuffle\` tinyint NOT NULL DEFAULT '0', \`is_loop\` tinyint NOT NULL DEFAULT '0', \`title\` varchar(255) NULL, \`url\` varchar(255) NULL, \`thumbnail\` varchar(255) NULL, \`silent\` tinyint NOT NULL DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`guild_id\`, \`channel_id\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
        await queryRunner.query(`CREATE TABLE \`playlist\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`user_id\` bigint(20) NOT NULL, \`name\` varchar(255) NOT NULL, \`title\` varchar(255) NOT NULL, \`url\` varchar(255) NOT NULL, \`shuffle\` tinyint NOT NULL DEFAULT '1', \`loop\` tinyint NOT NULL DEFAULT '1', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
        await queryRunner.query(`CREATE TABLE \`room\` (\`room_id\` bigint(20) NOT NULL, \`guild_id\` bigint(20) NOT NULL, \`name\` varchar(255) NOT NULL, \`is_autodelete\` tinyint(1) NOT NULL DEFAULT '1', \`is_live\` tinyint(1) NOT NULL DEFAULT '0', \`is_private\` tinyint(1) NOT NULL DEFAULT '0', \`deleted_at\` datetime(6) NULL, \`updated_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`room_id\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
        await queryRunner.query(`CREATE TABLE \`speaker\` (\`guild_id\` bigint(20) NOT NULL, \`user_id\` bigint(20) NOT NULL, \`is_used\` tinyint(1) NOT NULL DEFAULT '0', PRIMARY KEY (\`guild_id\`, \`user_id\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
        await queryRunner.query(`ALTER TABLE \`chat_history\` ADD CONSTRAINT \`FK_021775dc564b487898fd99c607a\` FOREIGN KEY (\`bot_id\`) REFERENCES \`bot_info\`(\`bot_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role\` ADD CONSTRAINT \`FK_7f9e3b8f3390b95e6222cc0c334\` FOREIGN KEY (\`guild_id\`) REFERENCES \`guild\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_b9800dffb36dd078074ee7f3327\` FOREIGN KEY (\`guild_id\`) REFERENCES \`guild\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_a3ffb1c0c8416b9fc6f907b7433\` FOREIGN KEY (\`id\`) REFERENCES \`user_setting\`(\`user_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`item\` ADD CONSTRAINT \`FK_1c9aed3a9bb80edb642d9132c30\` FOREIGN KEY (\`rare\`) REFERENCES \`item_rank\`(\`rare\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`gacha\` ADD CONSTRAINT \`FK_4583531d245402e1112985a7af7\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`gacha\` ADD CONSTRAINT \`FK_d38f56e94ac2df4fc36909d00ed\` FOREIGN KEY (\`item_id\`) REFERENCES \`item\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`gacha\` DROP FOREIGN KEY \`FK_d38f56e94ac2df4fc36909d00ed\``);
        await queryRunner.query(`ALTER TABLE \`gacha\` DROP FOREIGN KEY \`FK_4583531d245402e1112985a7af7\``);
        await queryRunner.query(`ALTER TABLE \`item\` DROP FOREIGN KEY \`FK_1c9aed3a9bb80edb642d9132c30\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_a3ffb1c0c8416b9fc6f907b7433\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_b9800dffb36dd078074ee7f3327\``);
        await queryRunner.query(`ALTER TABLE \`role\` DROP FOREIGN KEY \`FK_7f9e3b8f3390b95e6222cc0c334\``);
        await queryRunner.query(`ALTER TABLE \`chat_history\` DROP FOREIGN KEY \`FK_021775dc564b487898fd99c607a\``);
        await queryRunner.query(`DROP TABLE \`speaker\``);
        await queryRunner.query(`DROP TABLE \`room\``);
        await queryRunner.query(`DROP TABLE \`playlist\``);
        await queryRunner.query(`DROP TABLE \`music_info\``);
        await queryRunner.query(`DROP TABLE \`music\``);
        await queryRunner.query(`DROP TABLE \`log\``);
        await queryRunner.query(`DROP TABLE \`gacha\``);
        await queryRunner.query(`DROP TABLE \`item\``);
        await queryRunner.query(`DROP INDEX \`IDX_381056f37abd6038609476869d\` ON \`item_rank\``);
        await queryRunner.query(`DROP TABLE \`item_rank\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`user_setting\``);
        await queryRunner.query(`DROP TABLE \`guild\``);
        await queryRunner.query(`DROP TABLE \`role\``);
        await queryRunner.query(`DROP TABLE \`color\``);
        await queryRunner.query(`DROP TABLE \`bot_info\``);
        await queryRunner.query(`DROP TABLE \`chat_history\``);
    }

}
